ov_json_rpc_api:
    swagger:
        api_v1:
            swagger_version: '1.2'
            api_version: '1'
            info:
                title: 'title'
                description: 'description'
                terms_of_service_url: 'terms_of_service_url'
                contact: 'contact'
                license: 'license'
                licenseUrl: 'licenseUrl'
