ov_json_rpc_api:
    swagger:
        api_v1:
            api_version: '1'
            base_path: '%env(string:OV_JSON_RPC_API_BASE_URL)%'
            info:
                title: 'title'
                description: 'description'
                terms_of_service_url: 'terms_of_service_url'
                contact:
                    name: 'name'
                    url: 'url'
                    email: 'email'
                license: 'license'
                licenseUrl: 'licenseUrl'
